### ISSUE TITLE
42pin Possible to program after build? Re-program?

### ISSUE THREAD

**Issue by Retrofletch** [OlegMishin/FlashROM#1]
Ive seen other other flashrom in 40pin form that can be programmed and re-programmed with an adapter, but your 42pin version would need a special adapter im guessing? How do you program these?
I can program the chips before i solder them, but what if i make misstake or i want to change contents? is it possible?
Thank you for releasing great projects!

**Comment by OlegMishin** [comment]
Hi, 
Only difference between 40 and 42 pin boards is A18 and A19 on pins 1 and 42. As the signals(A18/A19) present also on a small connetor, the same adapter(I use it with TL866 programmer) can be used to reprogram the Flash. I made an adapter board, a clone of TL866's TSOP48 adapter and will publish it later. It is based on this circuit:
https://proghq.org/wiki/index.php/TL866_TSOP48_adapter

Regards
Oleg

**Comment by Retrofletch** [comment]
Ok that makes sense, should be easy to do then as i have the TL866 adapter, thanks
